version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    assignees:
      - "etc-tiago"
    reviewers:
      - "etc-tiago"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers:
      - "etc-tiago"
    labels:
      - "dependencies"
