name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "12.16.x"
      - uses: actions/checkout@v1

      - name: Install
        run: yarn install --silent --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

  changelog:
    needs: [test]
    name: Chanegelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: etcdigital/pull-request-changelog@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
